name: Docker Compose Development Stack

on:
  push:
    branches: [ master ]

jobs:
  test-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment file
        run: |
          cat > .env << 'EOF'
          NODE_ENV=development
          PORT=3000
          DATABASE_TYPE=postgres
          DATABASE_HOST=postgres
          DATABASE_PORT=5432
          DATABASE_USERNAME=postgres
          DATABASE_PASSWORD=digitmindreason
          DATABASE_NAME=articles
          REDIS_URL=redis://redis:6379
          JWT_SECRET=super-secret-key
          JWT_EXPIRES_IN=1d
          EOF

      - name: Build and start all services
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yml"
          run-command: |
            up -d --build --force-recreate

      - name: Verify services are running
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yml"
          run-command: |
            ps
            logs --tail=10 app
            logs --tail=10 postgres
            logs --tail=10 redis

      - name: Cleanup
        if: always()
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yml"
          run-command: "down -v --remove-orphans"